import type { Locale } from '../i18n';

export const storefrontCopy = {
  en: {
    acceptingOrders: 'Accepting orders',
    shopNow: 'Shop now',
    learnMore: 'Learn more',
    featuredProducts: 'Featured products',
    item: 'item',
    items: 'items',
    emptyTitle: 'A fresh collection is coming soon',
    emptyBody: 'This store is preparing its first products. Check back shortly for the launch collection.',
    addToCart: 'Add to cart',
    cart: 'Your cart',
    emptyCart: 'Your cart is empty',
    emptyCartBody: 'Add products from the catalog to get started.',
    quantity: 'Quantity',
    remove: 'Remove',
    subtotal: 'Subtotal',
    checkoutNote: 'Shipping and taxes are confirmed at checkout.',
    checkout: 'Proceed to checkout',
    backToShop: 'Back to shop',
    checkoutTitle: 'Checkout',
    checkoutSubtitle: 'Choose Paymob online payment or cash on delivery.',
    billingTitle: 'Billing and shipping details',
    firstName: 'First name',
    lastName: 'Last name',
    email: 'Email address',
    phone: 'Phone number',
    street: 'Street address',
    city: 'City',
    paymentMethod: 'Payment method',
    payOnline: 'Online payment',
    payOnlineDesc: 'Mock checkout on free tier, Paymob when configured.',
    cod: 'Cash on delivery',
    codDesc: 'Collect payment when staff fulfills the order.',
    placeOrder: 'Place order',
    processing: 'Processing order...',
    orderReceived: 'Order received',
    orderThanks: 'Thank you for buying from',
    orderRef: 'Order reference',
    continueShopping: 'Continue shopping',
  },
  ar: {
    acceptingOrders: 'نستقبل الطلبات',
    shopNow: 'تسوق الآن',
    learnMore: 'اعرف المزيد',
    featuredProducts: 'منتجات مختارة',
    item: 'منتج',
    items: 'منتجات',
    emptyTitle: 'تشكيلة جديدة قريباً',
    emptyBody: 'المتجر يجهز أول منتجاته. عد قريباً لمشاهدة مجموعة الإطلاق.',
    addToCart: 'أضف إلى السلة',
    cart: 'سلة التسوق',
    emptyCart: 'السلة فارغة',
    emptyCartBody: 'أضف منتجات من الكتالوج للبدء.',
    quantity: 'الكمية',
    remove: 'حذف',
    subtotal: 'الإجمالي الفرعي',
    checkoutNote: 'يتم تأكيد الشحن والضرائب عند الدفع.',
    checkout: 'إتمام الطلب',
    backToShop: 'العودة للمتجر',
    checkoutTitle: 'إتمام الطلب',
    checkoutSubtitle: 'اختر الدفع الإلكتروني عبر باي موب أو الدفع عند الاستلام.',
    billingTitle: 'بيانات الشحن والدفع',
    firstName: 'الاسم الأول',
    lastName: 'اسم العائلة',
    email: 'البريد الإلكتروني',
    phone: 'رقم الهاتف',
    street: 'عنوان الشارع',
    city: 'المدينة',
    paymentMethod: 'طريقة الدفع',
    payOnline: 'الدفع الإلكتروني',
    payOnlineDesc: 'دفع تجريبي في الخطة المجانية، وباي موب عند التفعيل.',
    cod: 'الدفع عند الاستلام',
    codDesc: 'يحصل فريق المتجر المبلغ عند تسليم الطلب.',
    placeOrder: 'تأكيد الطلب',
    processing: 'جاري تنفيذ الطلب...',
    orderReceived: 'تم استلام الطلب',
    orderThanks: 'شكراً لتسوقك من',
    orderRef: 'رقم الطلب',
    continueShopping: 'متابعة التسوق',
  },
} satisfies Record<Locale, Record<string, string>>;

export function getStorefrontCopy(locale: string | null | undefined) {
  return storefrontCopy[locale === 'ar' ? 'ar' : 'en'];
}

export function pickLocalized(value: Record<Locale, string> | string | undefined, locale: Locale): string {
  if (!value) return '';
  if (typeof value === 'string') return value;
  return value[locale] || value.en || value.ar || '';
}
